### ISSUE TITLE
min.js version always returns  NOSPEECH: "1"

### ISSUE THREAD

**Issue by ToonTalk** [Azure-Samples/Cognitive-Speech-STT-JavaScript#33]
When I replaced speech.1.0.0.js with speech.1.0.0.min.js

the server always returns

{status: "error", properties: {requestid: "60150f0e-5dfd-4211-927d-608c8a3d36c0", NOSPEECH: "1"}}

Works fine otherwise. Windows 10 both in Edge and Chrome.

**Comment by priyaravi20** [comment]
Please use the latest JavaScript SDK. https://github.com/Azure-Samples/SpeechToText-WebSockets-JavaScript. This  SDK is not supported anymore.
